project:
  type: website

website:
  title: "Rossella Anania | Astrophysicist"
  description: "Personal website of Rossella Anania, astrophysicist working on astronomy, star formation and planet formation, protoplanetary and debris disc evolution."
  site-url: "https://rossella4712.github.io"

  navbar:
    background: '#e52b50'
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: phd_thesis.qmd
        text: PhD Thesis
      - href: research.qmd
        text: Research
      - href: interests.qmd
        text: Interests

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="Pryb_QcsjmsVjY6xUGTPBh5fM0MROK3X_Ter33VuGN0" />
